http://www.highprogrammer.com/alan/numbers/mrp.html#countrycodes

codes = {
    "AFG":"Afghanistan",
    "ALB":"Albania",
    "DZA":"Algeria",
    "ASM":"American Samoa",
    "AND":"Andorra",
    "AGO":"Angola",
    "AIA":"Anguilla",
    "ATA":"Antarctica",
    "ATG":"Antigua and Barbuda",
    "ARG":"Argentina",
    "ARM":"Armenia",
    "ABW":"Aruba",
    "AUS":"Australia",
    "AUT":"Austria",
    "AZE":"Azerbaijan",
    "BHS":"Bahamas",
    "BHR":"Bahrain",
    "BGD":"Bangladesh",
    "BRB":"Barbados",
    "BLR":"Belarus",
    "BEL":"Belgium",
    "BLZ":"Belize",
    "BEN":"Benin",
    "BMU":"Bermuda",
    "BTN":"Bhutan",
    "BOL":"Bolivia",
    "BIH":"Bosnia and Herzegovina",
    "BWA":"Botswana",
    "BVT":"Bouvet Island",
    "BRA":"Brazil",
    "IOT":"British Indian Ocean Territory",
    "BRN":"Brunei",
    "BGR":"Bulgaria",
    "BFA":"Burkina Faso",
    "BDI":"Burundi",
    "KHM":"Cambodia",
    "CMR":"Cameroon",
    "CAN":"Canada",
    "CPV":"Cape Verde",
    "CYM":"Cayman Islands",
    "CAF":"Central African Republic",
    "TCD":"Chad",
    "CHL":"Chile",
    "CHN":"China",
    "CXR":"Christmas Island",
    "CCK":"Cocos (Keeling) Islands",
    "COL":"Colombia",
    "COM":"Comoros",
    "COG":"Congo",
    "COK":"Cook Islands",
    "CRI":"Costa Rica",
    "CIV":"Côte d'Ivoire",
    "HRV":"Croatia",
    "CUB":"Cuba",
    "CYP":"Cyprus",
    "CZE":"Czech Republic",
    "PRK":"Democratic People's Republic of Korea",
    "COD":"Democratic Republic of the Congo",
    "DNK":"Denmark",
    "DJI":"Djibouti",
    "DMA":"Dominica",
    "DOM":"Dominican Republic",
    "TMP":"East Timor",
    "ECU":"Ecuador",
    "EGY":"Egypt",
    "SLV":"El Salvador",
    "GNQ":"Equatorial Guinea",
    "ERI":"Eritrea",
    "EST":"Estonia",
    "ETH":"Ethiopia",
    "FLK":"Falkland Islands",
    "FRO":"Faeroe Islands",
    "FJI":"Fiji",
    "FIN":"Finland",
    "FRA":"France",
    "FXX":"France, Metropolitan",
    "GUF":"French Guiana",
    "PYF":"French Polynesia",
    "GAB":"Gabon",
    "GMB":"Gambia",
    "GEO":"Georgia",
    "D<<":"Germany",
    "GHA":"Ghana",
    "GIB":"Gibraltar",
    "GRC":"Greece",
    "GRL":"Greenland",
    "GRD":"Grenada",
    "GLP":"Guadeloupe",
    "GUM":"Guam",
    "GTM":"Guatemala",
    "GIN":"Guinea",
    "GNB":"Guinea-Bissau",
    "GUY":"Guyana",
    "HTI":"Haiti",
    "HMD":"Heard and McDonald Islands",
    "VAT":"Holy See (Vatican City)",
    "HND":"Honduras",
    "HKG":"Hong Kong",
    "HUN":"Hungary",
    "ISL":"Iceland",
    "IND":"India",
    "IDN":"Indonesia",
    "IRN":"Iran",
    "IRQ":"Iraq",
    "IRL":"Ireland",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    
    
}